gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - default
  showCommandLog: false
  nerdFontsVersion: "3"
  showFileTree: true
  sidePanelWidth: 0.3333
git:
  paging:
    colorArg: always
  commit:
    signOff: false
  autoFetch: true
  parseEmoji: true
os:
  editPreset: "nvim"
