#!/usr/bin/env bash
# Regenerate superfile's "athome" theme to match the active `theme` pick + the
# current system dark/light, so the file manager follows the picker. superfile
# reads its theme fresh on every launch, so the spf() shell wrapper runs this
# just before launching (and ~/.local/bin/theme runs it on a pick).
#
# superfile's bundled themes are mostly dark-only (no gruvbox/everforest light),
# so — like gh-dash — we generate a full hex theme from registry.sh::theme_palette
# instead of mapping to a built-in. The generated theme file lives in superfile's
# DATA dir (not chezmoi-managed), so this produces no config drift; config.toml
# just pins `theme = 'athome'`.
set -euo pipefail

dir="${HOME}/.config/themes"
# shellcheck source=/dev/null
. "$dir/registry.sh"

# superfile's theme folder (data dir/theme): macOS uses Application Support,
# Linux uses XDG_DATA_HOME. Matches `spf --debug-info`'s "Theme Folder".
case "$(uname -s)" in
  Darwin) tf="$HOME/Library/Application Support/superfile/theme" ;;
  *)      tf="${XDG_DATA_HOME:-$HOME/.local/share}/superfile/theme" ;;
esac
mkdir -p "$tf" || exit 0

family="$(cat "$dir/active" 2>/dev/null || echo gruvbox)"

# Current appearance → mode (default light, matching the light-first palettes).
mode=light
case "$(uname -s)" in
  Darwin) [ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = Dark ] && mode=dark ;;
  *)      case "$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null)" in
            *dark*) mode=dark ;;
          esac ;;
esac

pal="$(theme_palette "$family" "$mode")"
[ -z "$pal" ] && pal="$(theme_palette gruvbox "$mode")"   # unknown family → safe default
eval "$pal"   # BG FG BLUE YELLOW GREEN GREY MUTED

# No red in the 7-colour palette → mode-appropriate red for error.
[ "$mode" = dark ] && ERR='#fb4934' || ERR='#9d0006'

cat > "$tf/athome.toml" <<EOF
# Generated by ~/.config/themes/apply-superfile.sh — do not edit.
# Tracks the active 'theme' pick ($family) + system $mode mode.
code_syntax_highlight = "gruvbox"

full_screen_fg = "$FG"
full_screen_bg = "$BG"
gradient_color = ["$GREEN", "$BLUE"]

file_panel_fg = "$FG"
file_panel_bg = "$BG"
file_panel_border = "$MUTED"
file_panel_border_active = "$YELLOW"
file_panel_top_directory_icon = "$GREEN"
file_panel_top_path = "$BLUE"
file_panel_item_selected_fg = "$BLUE"
file_panel_item_selected_bg = "$BG"

footer_fg = "$FG"
footer_bg = "$BG"
footer_border = "$MUTED"
footer_border_active = "$YELLOW"

sidebar_fg = "$FG"
sidebar_bg = "$BG"
sidebar_title = "$BLUE"
sidebar_border = "$BG"
sidebar_border_active = "$YELLOW"
sidebar_item_selected_fg = "$YELLOW"
sidebar_item_selected_bg = "$BG"
sidebar_divider = "$MUTED"

modal_fg = "$FG"
modal_bg = "$BG"
modal_border_active = "$MUTED"
modal_cancel_fg = "$FG"
modal_cancel_bg = "$GREY"
modal_confirm_fg = "$BG"
modal_confirm_bg = "$GREEN"

help_menu_hotkey = "$GREEN"
help_menu_title = "$YELLOW"

cursor = "$GREEN"
correct = "$GREEN"
error = "$ERR"
hint = "$BLUE"
cancel = "$GREY"
EOF
